#!/usr/bin/env Rscript
# Run the Table 8-style KEGG and Reactome enrichment for one-gene-per-line
# input files. The input files are generated by build_gene_inputs.py.
#
# Usage:
#   Rscript run_stringdb_enrichment.R INPUT_DIR OUTPUT_DIR [SCORE] [CACHE_DIR]
#
# The default background is STRING's genome background, matching the original
# Enrichment/stringDBScript.R (no set_background call).

suppressPackageStartupMessages(library(STRINGdb))

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2L || length(args) > 4L) {
  stop("Usage: run_stringdb_enrichment.R INPUT_DIR OUTPUT_DIR [SCORE] [CACHE_DIR]")
}

input_dir <- normalizePath(args[[1]], mustWork = TRUE)
output_dir <- args[[2]]
score_threshold <- if (length(args) >= 3L) as.integer(args[[3]]) else 400L
cache_dir <- if (length(args) >= 4L) args[[4]] else file.path(output_dir, "stringdb_cache")

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(cache_dir, recursive = TRUE, showWarnings = FALSE)

string_db <- STRINGdb$new(
  version = "12.0",
  species = 9606,
  score_threshold = score_threshold,
  input_directory = cache_dir
)

find_column <- function(data, exact = character(), patterns = character()) {
  columns <- names(data)
  exact_match <- columns[tolower(columns) %in% tolower(exact)]
  if (length(exact_match) > 0L) return(exact_match[[1]])
  for (pattern in patterns) {
    match <- columns[grepl(pattern, columns, ignore.case = TRUE)]
    if (length(match) > 0L) return(match[[1]])
  }
  NA_character_
}

as_numeric_fdr <- function(x) {
  suppressWarnings(as.numeric(as.character(x)))
}

input_files <- sort(list.files(input_dir, pattern = "\\.txt$", full.names = TRUE))
if (length(input_files) == 0L) stop("No .txt gene-list files found in INPUT_DIR")

mapping_rows <- list()
result_rows <- list()
row_index <- 1L

for (input_file in input_files) {
  dataset <- tools::file_path_sans_ext(basename(input_file))
  genes <- unique(trimws(readLines(input_file, warn = FALSE)))
  genes <- genes[nzchar(genes)]
  gene_data <- data.frame(gene = genes, stringsAsFactors = FALSE)
  mapped <- string_db$map(gene_data, "gene", removeUnmappedRows = TRUE)
  mapped_ids <- unique(mapped$STRING_id)

  mapping_rows[[length(mapping_rows) + 1L]] <- data.frame(
    dataset = dataset,
    input_genes = length(genes),
    mapped_rows = nrow(mapped),
    mapped_string_ids = length(mapped_ids),
    unmapped_genes = length(setdiff(genes, mapped$gene)),
    stringsAsFactors = FALSE
  )

  # STRINGdb names Reactome "RCTM" in the enrichment API.
  database_categories <- c(KEGG = "KEGG", Reactome = "RCTM")
  for (database_name in names(database_categories)) {
    category <- unname(database_categories[[database_name]])
    enrichment <- as.data.frame(
      string_db$get_enrichment(mapped_ids, category = category),
      stringsAsFactors = FALSE
    )
    raw_path <- file.path(output_dir, paste0(dataset, "__", database_name, ".csv"))
    write.csv(enrichment, raw_path, row.names = FALSE)
    if (nrow(enrichment) == 0L) next

    pathway_column <- find_column(
      enrichment,
      exact = c("description", "term description", "term_description"),
      patterns = c("description", "term.*name", "term")
    )
    fdr_column <- find_column(
      enrichment,
      exact = c("FDR value", "fdr", "false discovery rate"),
      patterns = c("fdr", "false.*discovery")
    )
    if (is.na(pathway_column) || is.na(fdr_column)) {
      stop(sprintf("Cannot identify pathway/FDR columns in %s", raw_path))
    }

    gene_count_column <- find_column(
      enrichment,
      exact = c("# genes", "number_of_genes", "number of genes"),
      patterns = c("genes")
    )
    normalized <- data.frame(
      dataset = dataset,
      database = database_name,
      pathway = as.character(enrichment[[pathway_column]]),
      fdr = as_numeric_fdr(enrichment[[fdr_column]]),
      genes_in_pathway = if (is.na(gene_count_column)) NA else as.character(enrichment[[gene_count_column]]),
      input_genes = length(genes),
      mapped_genes = length(mapped_ids),
      stringsAsFactors = FALSE
    )
    result_rows[[row_index]] <- normalized
    row_index <- row_index + 1L
  }
}

mapping <- do.call(rbind, mapping_rows)
write.csv(mapping, file.path(output_dir, "mapping_summary.csv"), row.names = FALSE)

# STRINGdb may return no rows for a database when the selected genes produce
# no returned pathway terms. Preserve that as an empty, valid result table.
if (length(result_rows) == 0L) {
  all_results <- data.frame(
    dataset = character(),
    database = character(),
    pathway = character(),
    fdr = numeric(),
    genes_in_pathway = character(),
    input_genes = integer(),
    mapped_genes = integer(),
    stringsAsFactors = FALSE
  )
} else {
  all_results <- do.call(rbind, result_rows)
  all_results <- all_results[!is.na(all_results$fdr), , drop = FALSE]
  all_results <- all_results[order(all_results$dataset, all_results$fdr, all_results$database, all_results$pathway), , drop = FALSE]
}
write.csv(all_results, file.path(output_dir, "all_pathways.csv"), row.names = FALSE)

# A pathway present in both databases is retained once, using its smallest FDR.
# This makes the requested top-10 table contain distinct biological pathways.
if (nrow(all_results) == 0L) {
  top10 <- all_results
  top10$rank <- integer()
} else {
  deduplicated <- all_results[!duplicated(all_results[c("dataset", "pathway")]), , drop = FALSE]
  by_dataset <- split(deduplicated, deduplicated$dataset)
  top_rows <- lapply(by_dataset, function(data) {
    data <- data[seq_len(min(10L, nrow(data))), , drop = FALSE]
    data$rank <- seq_len(nrow(data))
    data
  })
  top10 <- do.call(rbind, top_rows)
}
top10 <- top10[, c("dataset", "rank", "database", "pathway", "fdr", "genes_in_pathway", "input_genes", "mapped_genes")]
row.names(top10) <- NULL
write.csv(top10, file.path(output_dir, "top10_pathways_single_cell.csv"), row.names = FALSE)

metadata <- data.frame(
  stringdb_version = "12.0",
  species = 9606L,
  score_threshold = score_threshold,
  background = "STRING genome (default)",
  databases = "KEGG;Reactome",
  ranking = "ascending FDR; duplicate pathway names retain smallest FDR",
  result_status = if (nrow(all_results) > 0L) "pathway rows returned" else "no KEGG/Reactome pathway rows returned",
  stringsAsFactors = FALSE
)
write.csv(metadata, file.path(output_dir, "run_metadata.csv"), row.names = FALSE)

cat(sprintf("Wrote %d top pathways to %s\n", nrow(top10), file.path(output_dir, "top10_pathways_single_cell.csv")))
