#!/usr/bin/env python3
"""Run one patient split's notebook-compatible Bayesian XGBoost search.

The split manifest is intentionally treated as data, rather than regenerated by
this script.  This makes each dataset/seed run independently reproducible and
keeps the test patients out of Bayesian tuning.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import anndata as ad
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[3]
MANIFEST_PATH = ROOT / "agent_log" / "multi_seed_splits" / "patient_assignments.csv"
DATASET_PATHS = {
    "CD4_CSF": ROOT / "paper" / "ML" / "Store" / "CD4_CSF_SAMU" / "datasetDeclustered.h5ad",
    "CSF_BCELLS": ROOT / "paper" / "ML" / "Store" / "CSF_BCELLS" / "datasetDeclustered.h5ad",
    "PBMC_BCELLS": ROOT / "paper" / "ML" / "Store" / "PBMC_BCELLS_2DATASET" / "datasetDeclustered.h5ad",
}
SPLITS = ("train", "validation", "test")
CONDITIONS = ("CTRL", "MS")
REQUIRED_MANIFEST_COLUMNS = {"dataset", "split_seed", "split", "patient", "condition", "cells"}

# These values are transcribed from the BayesSearchCV cells in each notebook.
# The description is also written to the result JSON so that a run is auditable
# without relying on pickled skopt objects.
SEARCH_SPACE_INFO: dict[str, dict[str, Any]] = {
    "CD4_CSF": {
        "classifier__n_estimators": {"kind": "Integer", "low": 50, "high": 600},
        "classifier__max_depth": {"kind": "Integer", "low": 2, "high": 15},
        "classifier__learning_rate": {"kind": "Real", "low": 0.001, "high": 0.7, "prior": "log-uniform"},
        "classifier__gamma": {"kind": "Real", "low": 0.0001, "high": 1.0, "prior": "log-uniform"},
        "classifier__min_child_weight": {"kind": "Integer", "low": 1, "high": 8},
        "classifier__scale_pos_weight": {"kind": "Categorical", "categories": [5263 / 8000]},
        "classifier__reg_alpha": {"kind": "Real", "low": 0.001, "high": 100.0, "prior": "log-uniform"},
        "classifier__reg_lambda": {"kind": "Real", "low": 0.001, "high": 100.0, "prior": "log-uniform"},
    },
    "CSF_BCELLS": {
        "classifier__n_estimators": {"kind": "Integer", "low": 50, "high": 3000},
        "classifier__max_depth": {"kind": "Integer", "low": 2, "high": 15},
        "classifier__learning_rate": {"kind": "Real", "low": 0.0000001, "high": 1.0, "prior": "log-uniform"},
        "classifier__gamma": {"kind": "Real", "low": 0.000001, "high": 1.0, "prior": "log-uniform"},
        "classifier__min_child_weight": {"kind": "Integer", "low": 1, "high": 8},
        "classifier__scale_pos_weight": {"kind": "Categorical", "categories": [1.0, 400 / 510]},
        "classifier__reg_alpha": {"kind": "Real", "low": 0.000001, "high": 100.0, "prior": "log-uniform"},
        "classifier__reg_lambda": {"kind": "Real", "low": 0.000001, "high": 100.0, "prior": "log-uniform"},
    },
    "PBMC_BCELLS": {
        "classifier__n_estimators": {"kind": "Integer", "low": 50, "high": 3000},
        "classifier__max_depth": {"kind": "Integer", "low": 2, "high": 15},
        "classifier__learning_rate": {"kind": "Real", "low": 0.0000001, "high": 1.0, "prior": "log-uniform"},
        "classifier__gamma": {"kind": "Real", "low": 0.000001, "high": 1.0, "prior": "log-uniform"},
        "classifier__min_child_weight": {"kind": "Integer", "low": 1, "high": 8},
        "classifier__scale_pos_weight": {"kind": "Categorical", "categories": [1.0, 439 / 1077, 4.0]},
        "classifier__reg_alpha": {"kind": "Real", "low": 0.000001, "high": 100.0, "prior": "log-uniform"},
        "classifier__reg_lambda": {"kind": "Real", "low": 0.000001, "high": 100.0, "prior": "log-uniform"},
    },
}


def _json_default(value: Any) -> Any:
    """Convert numpy/skopt-adjacent scalar values for JSON output."""
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if isinstance(value, Path):
        return str(value)
    raise TypeError(f"Cannot JSON encode {type(value).__name__}")


def _atomic_write(path: Path, writer: Any, mode: str = "w", encoding: str = "utf-8") -> None:
    """Write a new result atomically, refusing to replace an existing result."""
    if path.exists():
        raise FileExistsError(f"Refusing to overwrite existing result: {path}")
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}-{uuid.uuid4().hex}")
    try:
        with temporary.open(mode, encoding=encoding, newline="") as handle:
            writer(handle)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _atomic_json(path: Path, value: Any) -> None:
    _atomic_write(path, lambda h: json.dump(value, h, indent=2, sort_keys=True, default=_json_default) or h.write("\n"))


def _prepare_output_dir(path: Path) -> Path:
    """Create an exclusive run directory and leave a marker while it runs."""
    path = path.expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if not path.is_dir():
            raise FileExistsError(f"Output path is not a directory: {path}")
        if any(path.iterdir()):
            raise FileExistsError(f"Output directory is not empty; refusing overwrite: {path}")
    else:
        path.mkdir()
    marker = path / ".running"
    fd = os.open(marker, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(f"pid={os.getpid()}\nstarted={datetime.now(timezone.utc).isoformat()}\n")
    return path


def _manifest_frame(path: Path) -> pd.DataFrame:
    if not path.is_file():
        raise FileNotFoundError(f"Patient assignment manifest not found: {path}")
    frame = pd.read_csv(path, dtype=str)
    missing = REQUIRED_MANIFEST_COLUMNS.difference(frame.columns)
    if missing:
        raise ValueError(f"Manifest is missing required columns: {sorted(missing)}")
    frame = frame[list(REQUIRED_MANIFEST_COLUMNS)].copy()
    frame["dataset"] = frame["dataset"].str.strip()
    frame["split"] = frame["split"].str.strip()
    frame["patient"] = frame["patient"].str.strip()
    frame["condition"] = frame["condition"].str.strip()
    frame["split_seed"] = frame["split_seed"].str.strip()
    if frame.isna().any().any() or (frame == "").any().any():
        raise ValueError("Manifest contains empty values")
    try:
        frame["cells"] = pd.to_numeric(frame["cells"], errors="raise").astype(int)
    except (TypeError, ValueError) as exc:
        raise ValueError("Manifest cells column must contain integers") from exc
    if (frame["cells"] <= 0).any():
        raise ValueError("Manifest cells counts must be positive")
    return frame


def _validate_and_plan(manifest: pd.DataFrame, dataset: str, seed: int, adata: ad.AnnData) -> dict[str, Any]:
    rows = manifest[(manifest["dataset"] == dataset) & (manifest["split_seed"] == str(seed))].copy()
    if rows.empty:
        raise ValueError(f"No manifest rows for dataset={dataset}, split_seed={seed}")
    if set(rows["split"]) != set(SPLITS):
        raise ValueError(f"Manifest must contain exactly {SPLITS} for {dataset}/{seed}")
    if rows.duplicated(["split", "patient"]).any():
        duplicate = rows.loc[rows.duplicated(["split", "patient"], keep=False), ["split", "patient"]]
        raise ValueError(f"Duplicate patient assignment: {duplicate.to_dict(orient='records')}")
    patient_condition = rows.groupby("patient")["condition"].nunique()
    if (patient_condition > 1).any():
        bad = patient_condition[patient_condition > 1].index.tolist()
        raise ValueError(f"Patient has inconsistent manifest conditions: {bad}")
    if not set(rows["condition"]).issubset(CONDITIONS):
        raise ValueError(f"Conditions must be exactly CTRL/MS; got {sorted(set(rows['condition']))}")

    if "sample" not in adata.obs or "condition" not in adata.obs:
        raise ValueError("Declustered h5ad must contain obs columns 'sample' and 'condition'")
    obs = adata.obs[["sample", "condition"]].copy()
    obs["sample"] = obs["sample"].astype(str).str.strip()
    obs["condition"] = obs["condition"].astype(str).str.strip()
    if not set(obs["condition"]).issubset(CONDITIONS):
        raise ValueError(f"Dataset conditions must be exactly CTRL/MS; got {sorted(set(obs['condition']))}")
    observed_patients = set(obs["sample"])
    manifest_patients = set(rows["patient"])
    if observed_patients != manifest_patients:
        raise ValueError(
            f"Manifest does not completely cover h5ad patients (missing={sorted(observed_patients - manifest_patients)}, "
            f"extra={sorted(manifest_patients - observed_patients)})"
        )
    observed_condition = obs.groupby("sample")["condition"].nunique()
    if (observed_condition > 1).any():
        bad = observed_condition[observed_condition > 1].index.tolist()
        raise ValueError(f"Patient has inconsistent h5ad conditions: {bad}")
    actual_condition = obs.groupby("sample")["condition"].first()
    manifest_condition = rows.drop_duplicates("patient").set_index("patient")["condition"]
    mismatch = [p for p in manifest_patients if actual_condition[p] != manifest_condition[p]]
    if mismatch:
        raise ValueError(f"Manifest/h5ad condition mismatch for patients: {sorted(mismatch)}")

    split_sets: dict[str, set[str]] = {}
    partitions: dict[str, dict[str, Any]] = {}
    for split in SPLITS:
        part = rows[rows["split"] == split]
        ids = set(part["patient"])
        split_sets[split] = ids
        for other in SPLITS:
            if split != other and ids.intersection(split_sets.get(other, set())):
                raise ValueError(f"Patient leakage between {split} and {other}")
        expected_counts = part.groupby("patient")["cells"].first()
        actual_counts = obs[obs["sample"].isin(ids)].groupby("sample").size()
        if not expected_counts.sort_index().equals(actual_counts.rename("cells").sort_index()):
            joined = pd.concat([expected_counts.rename("manifest"), actual_counts.rename("h5ad")], axis=1)
            raise ValueError(f"Manifest/h5ad cell count mismatch in {split}: {joined.to_dict(orient='index')}")
        condition_counts = part["condition"].value_counts().to_dict()
        if set(condition_counts) != set(CONDITIONS):
            raise ValueError(f"Each {split} partition must contain both conditions; got {condition_counts}")
        row_count = int(actual_counts.sum())
        partitions[split] = {
            "patients": sorted(ids),
            "patient_count": len(ids),
            "cell_count": row_count,
            "condition_patient_counts": {condition: int(condition_counts.get(condition, 0)) for condition in CONDITIONS},
            "condition_cell_counts": {
                condition: int(obs[(obs["sample"].isin(ids)) & (obs["condition"] == condition)].shape[0])
                for condition in CONDITIONS
            },
            "shape": [row_count, int(adata.n_vars)],
        }
    if set().union(*split_sets.values()) != observed_patients:
        raise ValueError("Split partitions do not cover all h5ad patients")
    return {
        "dataset": dataset,
        "split_seed": seed,
        "input_path": str(DATASET_PATHS[dataset]),
        "n_obs": int(adata.n_obs),
        "n_features": int(adata.n_vars),
        "partitions": partitions,
    }


def _matrix_for(adata: ad.AnnData, patients: Iterable[str]) -> Any:
    from scipy import sparse

    patient_set = set(patients)
    sample = adata.obs["sample"].astype(str).to_numpy()
    mask = np.isin(sample, list(patient_set))
    matrix = adata.X[mask]
    if sparse.issparse(matrix):
        return matrix.tocsr()
    return np.asarray(matrix, dtype=np.float32)


def _dense(matrix: Any) -> np.ndarray:
    from scipy import sparse

    if sparse.issparse(matrix):
        return matrix.toarray().astype(np.float32, copy=False)
    return np.asarray(matrix, dtype=np.float32)


def _search_spaces(dataset: str) -> dict[str, Any]:
    from skopt.space import Categorical, Integer, Real

    info = SEARCH_SPACE_INFO[dataset]
    result: dict[str, Any] = {}
    for name, spec in info.items():
        if spec["kind"] == "Integer":
            result[name] = Integer(spec["low"], spec["high"])
        elif spec["kind"] == "Real":
            result[name] = Real(spec["low"], spec["high"], prior=spec["prior"])
        else:
            result[name] = Categorical(spec["categories"])
    return result


def _scorers() -> dict[str, Any]:
    from sklearn.metrics import f1_score, make_scorer, precision_score, recall_score

    # Binary pos_label scorers are equivalent to the notebook's
    # average=None[index] functions and remain joblib-portable when this file
    # is executed as a script.
    return {
        "Accuracy": "accuracy",
        "precision 0": make_scorer(precision_score, pos_label=0),
        "precision 1": make_scorer(precision_score, pos_label=1),
        "recall 0": make_scorer(recall_score, pos_label=0),
        "recall 1": make_scorer(recall_score, pos_label=1),
        "f1": make_scorer(f1_score, average="macro"),
    }


def _metrics(model: Any, x: Any, y: np.ndarray, split: str) -> dict[str, Any]:
    from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score

    prediction = np.asarray(model.predict(x)).astype(int)
    result: dict[str, Any] = {
        "split": split,
        "n_obs": int(len(y)),
        "accuracy": float(accuracy_score(y, prediction)),
        "precision": float(precision_score(y, prediction, zero_division=0)),
        "recall": float(recall_score(y, prediction, zero_division=0)),
        "f1": float(f1_score(y, prediction, zero_division=0)),
        "f1_macro": float(f1_score(y, prediction, average="macro", zero_division=0)),
    }
    try:
        probability = np.asarray(model.predict_proba(x))[:, 1]
        result["roc_auc"] = float(roc_auc_score(y, probability))
    except (AttributeError, ValueError):
        result["roc_auc"] = None
    return result


def _csv_metrics(path: Path, metrics: list[dict[str, Any]]) -> None:
    fields = ["split", "n_obs", "accuracy", "precision", "recall", "f1", "f1_macro", "roc_auc"]

    def write(handle: Any) -> None:
        output = csv.DictWriter(handle, fieldnames=fields)
        output.writeheader()
        output.writerows(metrics)

    _atomic_write(path, write)


def _run_search(dataset: str, seed: int, plan: dict[str, Any], adata: ad.AnnData, iterations: int, output: Path) -> None:
    from imblearn.combine import SMOTETomek
    from imblearn.pipeline import Pipeline
    from sklearn.model_selection import PredefinedSplit
    from sklearn.preprocessing import MinMaxScaler
    from xgboost import XGBClassifier
    from skopt import BayesSearchCV

    logger = logging.getLogger("multiseed")
    patients = plan["partitions"]
    raw = {split: _matrix_for(adata, patients[split]["patients"]) for split in SPLITS}
    labels = {
        split: (adata.obs.loc[adata.obs["sample"].astype(str).isin(patients[split]["patients"]), "condition"] == "MS").astype(int).to_numpy()
        for split in SPLITS
    }
    # Notebook preprocessing is applied to training only; validation and test
    # remain untouched.  The CD4 notebook's visible narrow search uses the
    # original x_train, whereas CSF/PBMC use SMOTETomek before tuning.
    if dataset == "CD4_CSF":
        x_train, y_train = raw["train"], labels["train"]
        logger.info("Using unresampled training matrix with shape %s", x_train.shape)
    else:
        x_train, y_train = SMOTETomek(random_state=42).fit_resample(raw["train"], labels["train"])
        logger.info("Resampled training matrix from %s to %s", raw["train"].shape, x_train.shape)
    x_train = _dense(x_train)
    x_val = _dense(raw["validation"])
    x_test = _dense(raw["test"])
    X = np.concatenate([x_train, x_val], axis=0)
    y = np.concatenate([y_train, labels["validation"]], axis=0)
    cv = PredefinedSplit(test_fold=[-1] * len(y_train) + [0] * len(labels["validation"]))

    estimator = Pipeline(
        steps=[
            ("scaling", MinMaxScaler()),
            (
                "classifier",
                XGBClassifier(
                    random_state=42,
                    device="cuda",
                    tree_method="hist",
                    objective="binary:logistic",
                    n_jobs=1,
                ),
            ),
        ]
    )
    search = BayesSearchCV(
        estimator=estimator,
        search_spaces=_search_spaces(dataset),
        cv=cv,
        n_iter=iterations,
        return_train_score=True,
        refit="f1",
        scoring=_scorers(),
        n_jobs=1,
        verbose=3,
        random_state=42,
    )
    logger.info("Starting BayesSearchCV: dataset=%s seed=%s n_iter=%s", dataset, seed, iterations)
    search.fit(X, y)
    logger.info("Search complete; best score=%s", search.best_score_)

    metrics = [
        _metrics(search, x_train, np.asarray(y_train, dtype=int), "train"),
        _metrics(search, x_val, labels["validation"], "validation"),
        _metrics(search, x_test, labels["test"], "test"),
    ]
    _csv_metrics(output / "metrics.csv", metrics)
    _atomic_json(output / "best_parameters.json", search.best_params_)
    joblib_path = output / "bayes_search.joblib"
    import joblib

    if joblib_path.exists():
        raise FileExistsError(f"Refusing to overwrite existing result: {joblib_path}")
    temporary = joblib_path.with_name(f".{joblib_path.name}.tmp-{os.getpid()}-{uuid.uuid4().hex}")
    try:
        joblib.dump(search, temporary, compress=3)
        os.replace(temporary, joblib_path)
    finally:
        temporary.unlink(missing_ok=True)

    summary = dict(plan)
    summary.update(
        {
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "dry_run": False,
            "search_iterations": iterations,
            "search_backend": "skopt.BayesSearchCV",
            "search_scoring": ["Accuracy", "precision 0", "precision 1", "recall 0", "recall 1", "f1"],
            "search_refit": "f1",
            "search_n_jobs": 1,
            "randomness": {
                "split_seed": seed,
                "model_random_state": 42,
                "sampler_random_state": 42,
                "search_random_state": 42,
                "note": "The manifest split seed is the only varying factor; fixed model/search RNG isolates split effects.",
            },
            "best_score": float(search.best_score_),
            "best_parameters": search.best_params_,
            "metrics": metrics,
            "train_resampling": "none (notebook CD4 narrow-search branch)" if dataset == "CD4_CSF" else "SMOTETomek(random_state=42)",
            "search_space": SEARCH_SPACE_INFO[dataset],
            "notebook_notes": [
                "Patient IDs and split membership come from the canonical manifest, replacing notebook hard-coded IDs/random seeds.",
                "Rows are cells; split boundaries are patient-level, matching the notebooks.",
                "The test partition is never supplied to BayesSearchCV and is evaluated only after refit.",
            ],
        }
    )
    _atomic_json(output / "summary.json", summary)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", required=True, choices=sorted(DATASET_PATHS))
    parser.add_argument("--split-seed", required=True, type=int, choices=(101, 202))
    parser.add_argument("--search-iterations", required=True, type=int, metavar="N")
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--dry-run", action="store_true", help="Validate and print the plan without fitting")
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH, help=argparse.SUPPRESS)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.search_iterations < 0:
        raise SystemExit("--search-iterations must be non-negative")
    if not args.dry_run and args.search_iterations == 0:
        raise SystemExit("positive --search-iterations is required unless --dry-run is used")
    input_path = DATASET_PATHS[args.dataset]
    if not input_path.is_file():
        raise SystemExit(f"Declustered input not found: {input_path}")

    manifest = _manifest_frame(args.manifest.expanduser().resolve())
    print(f"Loading {input_path}", flush=True)
    adata = ad.read_h5ad(input_path)
    plan = _validate_and_plan(manifest, args.dataset, args.split_seed, adata)
    plan["search_iterations"] = args.search_iterations
    plan["search_space"] = SEARCH_SPACE_INFO[args.dataset]
    plan["dry_run"] = bool(args.dry_run)
    plan["search_scoring"] = ["Accuracy", "precision 0", "precision 1", "recall 0", "recall 1", "f1"]
    plan["search_refit"] = "f1"
    plan["train_resampling"] = "none (notebook CD4 narrow-search branch)" if args.dataset == "CD4_CSF" else "SMOTETomek(random_state=42)"
    plan["randomness"] = {
        "split_seed": args.split_seed,
        "model_random_state": 42,
        "sampler_random_state": 42,
        "search_random_state": 42,
        "note": "The manifest split seed is the only varying factor; fixed model/search RNG isolates split effects.",
    }

    print(json.dumps(plan, indent=2, sort_keys=True, default=_json_default), flush=True)
    if args.dry_run:
        print("Dry run: validation passed; no model fitting performed.", flush=True)
        return 0

    output = _prepare_output_dir(args.output_dir)
    log_path = output / "run.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
        handlers=[logging.FileHandler(log_path), logging.StreamHandler(sys.stderr)],
        force=True,
    )
    try:
        _run_search(args.dataset, args.split_seed, plan, adata, args.search_iterations, output)
        (output / ".running").unlink(missing_ok=True)
    except Exception:
        logging.getLogger("multiseed").exception("Search failed")
        raise
    print(f"Results written to {output}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
